### ISSUE TITLE
User scene

### ISSUE THREAD

**Issue by dmr1987** [niceboygithub/AqaraSmartSwitchS1E#4]
Please uncomment line 299 at ubus_monitor.sh.
Methood **scservice_perform()** work great with HomeAssistant MQTT.
For scene cotrol i create location for every switch, and create empty automations with action **switch off all devices in this room**.

After that in Aqara App i create screen with 9 buttons, and for every button set different automation.

In home assisatant i use trigger for MQTT
```
alias: S1E_1.Some_Action
description: ""
trigger:
  - platform: mqtt
    topic: homeassistant/binary_sensor/0x00xxxxxxxx/al_10523645/set
    payload: "ON"
condition: []
action:
  - device_id: xxxxxxxxxx
mode: single

```
